apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: eda-qm
  namespace: mq01-dev
spec:
  license:
    accept: true
    license: L-QYVA-B365MB
    use: NonProduction
  queueManager:
    storage:
      defaultClass: ocs-storagecluster-ceph-rbd
      queueManager:
        type: persistent-claim
        size: 5Gi
    name: EDA_QM
    mqsc:
      - configMap:
          items:
            - config.mqsc
          name: eda-qm-configmap  
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 2Gi
    route:
      enabled: true
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  web:
    enabled: true
  version: 9.4.1.0-r2
  pki:
    keys:
      - name: default
        secret:
          items:
            - tls.crt
            - tls.key
          secretName: eda-qm-secret
    
